# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Accord Project on AWS
  SAM Template to deploy and execute Accord Project contracts on AWS
Parameters:
  ContractTemplatesRepositoryS3BucketName:
    Type: String
    Description: >
      A name of an S3 bucket storing Accord Project contract templates.
  QLDBContractLedgerName:
    Type: String
    Description: >
      A name of a QLDB ledger to keep the state of instantiated Accord Project contracts.
  EventsQueueName:
    Type: String
    Description: >
      A name of an SQS queue to send events, emitted during the contract execution.
Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 180
    Handler: index.handler
    Environment:
      Variables:
        AWS_REGION_NAME: !Sub "${AWS::Region}"
        KVS_LIB_PATH: "/opt/nodejs/lib/amazon-qldb-kvs-nodejs"
        ACCORD_S3_CONTRACTS_REPO_NAME: !Ref S3ContractTemplatesRepositoryBucket
        ACCORD_LEDGER_NAME: !Ref QLDBContractLedgerName
        ACCORD_EVENTS_QUEUE_NAME: !Ref EventsQueueName
        ACCORD_EVENTS_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EventsQueueName}"
Resources:
  #####
  # Lambda layer:
  #
  depLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-cicero-sam-dependencies"
      Description: Dependencies for sam app [node_modules, lib]
      ContentUri: ../dependencies/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: "Apache2"
      RetentionPolicy: Delete
  #####
  # Lambdas:
  #
  accorddeploy:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs10.x
      CodeUri: ../fcn-accord-deploy/
      Description: "Lambda function that helps to deploy Accord Project Contract"
      MemorySize: 512
      Timeout: 900
      Role: !GetAtt AccordLambdaRole.Arn
      FunctionName: !Sub "${AWS::StackName}-accord-deploy"
      Layers:
        - !Ref depLayer
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref AMBDevOpsSecurityGroupID
      #   SubnetIds:
      #     - !Ref AMBDevOpsPrivateSubnet1ID
      #     - !Ref AMBDevOpsPrivateSubnet2ID
      Tags:
        AccordContracts: AccordDeploy
  accordexecute:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs10.x
      CodeUri: ../fcn-accord-execute/
      Description: "Lambda function that helps to execute Accord Project Contract"
      MemorySize: 512
      Timeout: 900
      Role: !GetAtt AccordLambdaRole.Arn
      FunctionName: !Sub "${AWS::StackName}-accord-execute"
      Layers:
        - !Ref depLayer
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref AMBDevOpsSecurityGroupID
      #   SubnetIds:
      #     - !Ref AMBDevOpsPrivateSubnet1ID
      #     - !Ref AMBDevOpsPrivateSubnet2ID
      Tags:
        AccordContracts: LambdaAccordExecute
  qldbgetrevision:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs10.x
      CodeUri: ../fcn-qldb-get-document-revision/
      Description: "Retrieve a specific revision of QLDB document by Document Id and full BlockAddress"
      MemorySize: 256
      Timeout: 900
      Role: !GetAtt AccordLambdaRole.Arn
      FunctionName: !Sub "${AWS::StackName}-qldb-get-document-revision"
      Layers:
        - !Ref depLayer
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref AMBDevOpsSecurityGroupID
      #   SubnetIds:
      #     - !Ref AMBDevOpsPrivateSubnet1ID
      #     - !Ref AMBDevOpsPrivateSubnet2ID
      Tags:
        AccordContracts: LambdaQLDBGetRevision
  qldbverify:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs10.x
      CodeUri: ../fcn-qldb-verify/
      Description: "Verify Ledger Metadata for a specific document against the Ledger"
      MemorySize: 128
      Timeout: 900
      Role: !GetAtt AccordLambdaRole.Arn
      FunctionName: !Sub "${AWS::StackName}-qldb-verify"
      Layers:
        - !Ref depLayer
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref AMBDevOpsSecurityGroupID
      #   SubnetIds:
      #     - !Ref AMBDevOpsPrivateSubnet1ID
      #     - !Ref AMBDevOpsPrivateSubnet2ID
      Tags:
        AccordContracts: LambdaQLDBVerify
  qldbvgethistory:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs10.x
      CodeUri: ../fcn-qldb-get-document-history/
      Description: "Get full document history from the ledger by document key"
      MemorySize: 128
      Timeout: 900
      Role: !GetAtt AccordLambdaRole.Arn
      FunctionName: !Sub "${AWS::StackName}-qldb-get-document-history"
      Layers:
        - !Ref depLayer
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref AMBDevOpsSecurityGroupID
      #   SubnetIds:
      #     - !Ref AMBDevOpsPrivateSubnet1ID
      #     - !Ref AMBDevOpsPrivateSubnet2ID
      Tags:
        AccordContracts: LambdaQLDBGetHistory
  qldbvgetmetadata:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs10.x
      CodeUri: ../fcn-qldb-get-document-metadata/
      Description: "Get full document metadata from the ledger by document key"
      MemorySize: 128
      Timeout: 900
      Role: !GetAtt AccordLambdaRole.Arn
      FunctionName: !Sub "${AWS::StackName}-qldb-get-document-metadata"
      Layers:
        - !Ref depLayer
      # VpcConfig:
      #   SecurityGroupIds:
      #     - !Ref AMBDevOpsSecurityGroupID
      #   SubnetIds:
      #     - !Ref AMBDevOpsPrivateSubnet1ID
      #     - !Ref AMBDevOpsPrivateSubnet2ID
      Tags:
        AccordContracts: LambdaQLDBGetMetadata
  #####
  # Setting ledger to keep the state:
  #
  QLDBLedger:
    Type: "AWS::QLDB::Ledger"
    Properties:
      DeletionProtection: true
      Name: !Ref QLDBContractLedgerName
      PermissionsMode: "ALLOW_ALL"
      Tags:
        - Key: AccordContracts
          Value: ContractStateLedger
  #####
  # Setting S3 to keep contract templates:
  #
  S3ContractTemplatesRepositoryBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ContractTemplatesRepositoryS3BucketName}-${AWS::Region}-${AWS::AccountId}"
      Tags:
        - Key: AccordContracts
          Value: ContractTemplatesRepository
  EventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref EventsQueueName
      DelaySeconds: 0
      VisibilityTimeout: 120
  #####
  # Defining IAM role:
  #
  AccordLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-AccordLambdaRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Tags:
        - Key: AccordContracts
          Value: AccordLambdaRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-CloudWatchLogsAndCloudFormationAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudformation:describeStacks
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: !Sub "${AWS::StackName}-VPCLambdaInstantiationAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                Resource: "*"
        - PolicyName: S3ReadWriteAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:GetObject
                Effect: Allow
                Resource: arn:aws:s3:::*/*
              - Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                Effect: Allow
                Resource: !Sub "arn:aws:s3:::${ContractTemplatesRepositoryS3BucketName}*/*"
        - PolicyName: !Sub "${AWS::StackName}-QLDBReadWriteAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - qldb:ExecuteStatement
                  - qldb:GetBlock
                  - qldb:ListLedgers
                  - qldb:ListJournalS3ExportsForLedger
                  - qldb:GetRevision
                  - qldb:ExportJournalToS3
                  - qldb:DescribeLedger
                  - qldb:SendCommand
                  - qldb:ListJournalS3Exports
                  - qldb:DescribeJournalS3Export
                  - qldb:GetDigest
                  - qldb:ListTagsForResource"
                Resource: !Sub "arn:aws:qldb:${AWS::Region}:${AWS::AccountId}:ledger/${QLDBContractLedgerName}"
        - PolicyName: !Sub "${AWS::StackName}-SQSPublishAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${EventsQueueName}"
Outputs:
  AccordDeployARN:
    Description: "Arn of accord deploy function"
    Value: !GetAtt accorddeploy.Arn
    Export:
      Name: !Sub "${AWS::StackName}-accord-deployARN"
  AccordExecuteARN:
    Description: "Arn of accord execute function"
    Value: !GetAtt accordexecute.Arn
    Export:
      Name: !Sub "${AWS::StackName}-accord-executeARN"
  QLDBGetDocRevisionARN:
    Description: "Arn of QLDB get document revision function"
    Value: !GetAtt qldbgetrevision.Arn
    Export:
      Name: !Sub "${AWS::StackName}-qldb-get-document-revisionARN"
  QLDBVerifyARN:
    Description: "Arn of QLDB verify function"
    Value: !GetAtt qldbverify.Arn
    Export:
      Name: !Sub "${AWS::StackName}-qldb-verifyARN"
  ContractLedgerName:
    Description: "Name of a QLDB ledger to keep contract state"
    Value: !Ref QLDBLedger
  ContractRepoS3BucketName:
    Description: "Name of an S3 bucket to keep contract templates repository"
    Value: !Ref S3ContractTemplatesRepositoryBucket
  EventsQueueARN:
    Description: "An ARN of an SQS queue for emitting contract events"
    Value: !GetAtt EventsQueue.Arn
  EventsQueueURL:
    Description: "A URL of an SQS queue for emitting contract events"
    Value: !Ref EventsQueue
